-- SHOW COMMAND

SHOW DATABASES;
SHOW DATABASES LIKE 'a%';
SHOW TABLES FROM Amazon;
SHOW TABLES FROM Amazon LIKE 'o%';
SHOW COLUMNS FROM orders FROM Amazon;
SHOW COLUMNS FROM orders FROM Amazon LIKE 's%';
SHOW PROCEDURE STATUS;
SHOW PROCEDURE STATUS WHERE Name LIKE 's%';
